/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  basicSidebar: [
    {
      type: 'autogenerated',
      dirName: 'basic',
    }
  ],
  pythonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'python',
    }
  ],
  labSidebar: [
    {
      type: 'autogenerated',
      dirName: 'lab',
    }
  ],
  spiderSidebar: [
    {
      type: 'autogenerated',
      dirName: 'spider',
    }
  ],
  gitSidebar: [
    {
      type: 'autogenerated',
      dirName: 'git',
    },
  ],
};

module.exports = sidebars;
